name: Deploy Chan-Ko Website to GCP

on:
  push:
    tags:
      - 'v*' # This will trigger the workflow for any tag starting with 'v'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --filter chan-ko-website

    - name: Build website
      run: VITE_ENVIRONMENT=prod VITE_CHANKO_WEBSITE_CONTACT_FORM_ENDPOINT=${{ secrets.CHANKO_WEBSITE_CONTACT_FORM_ENDPOINT }} pnpm --filter chan-ko-website build

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.CHANKO_WEBSITE_GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.CHANKO_WEBSITE_GCP_PROJECT_ID }}

    - name: Deploy to GCP
      env:
        DOMAIN: chan-ko.com
        CERTBOT_EMAIL: ${{ secrets.CHANKO_DEVOPS_EMAIL }}
      run: |
        chmod +x ./deploy-chan-ko-website.sh
        ./deploy-chan-ko-website.sh "$DOMAIN" "$CERTBOT_EMAIL" "${{ secrets.CHANKO_WEBSITE_GCE_INSTANCE_NAME }}" "${{ secrets.CHANKO_WEBSITE_GCE_ZONE }}"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
