name: "Testing and Linting"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Enter devenv shell
      run: devenv shell

    - name: Install Node dependencies
      run: pnpm install

    - name: Run any pre-commit hooks
      run: devenv test
